Name: Pruthvik Kakadiya

UTA ID: 1001861545

Machine Learning (CSE-6363)

Programming Assignment 1

Matrix Factorization

In [149]:
import numpy
import pandas as pd

In [150]:
def matrix_factorization(Matrix, P, Q, K, iterations=1000, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in range(iterations):
        for i in range(len(Matrix)):
            for j in range(len(Matrix[i])):
                if Matrix[i][j] > 0:
                    element_ij = Matrix[i][j] - numpy.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * element_ij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * element_ij * P[i][k] - beta * Q[k][j])
        eR = numpy.dot(P,Q)
        error = 0
        for i in range(len(Matrix)):
            for j in range(len(Matrix[i])):
                if Matrix[i][j] > 0:
                    error = error + pow(Matrix[i][j] - numpy.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        error = error + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        if error < 0.001:
            break
    print("Matrix Factorization Completed")
    return P, Q.T

Try algorithm for a small test matrix

In [151]:
test_matrix = [[10,0,6,2],
               [6,3,0,0],
               [2,0,9,5]]
test = numpy.array(test_matrix)
N_test = len(test)
M_test = len(test[0])
K_test = 2
P_test = numpy.random.rand(N_test,K_test)
Q_test = numpy.random.rand(M_test,K_test)
new_P_test, new_Q_test = matrix_factorization(test, P_test, Q_test, K_test)
new_test_matrix = numpy.dot(new_P_test, new_Q_test.T)

Matrix Factorization Completed

Print the new test_matrix

In [152]:
new_test_matrix

array([[8.89564532, 3.92824798, 6.81045466, 2.48603253],
       [6.03460365, 2.78226786, 5.71446221, 2.39716167],
       [3.35255563, 2.05708911, 7.94047582, 4.42659599]])

Now take input1-1.csv file as input and run matrix factorization on that input file

In [153]:
input_matrix1 = pd.read_csv("input1-1.csv", header=None)
input_matrix1

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,6,0,3,7,2,5,4,2,4,3,...,1,6,4,8,6,0,0,3,9,1
1,2,0,0,8,7,3,1,2,2,0,...,8,7,3,5,2,4,6,6,8,1
2,0,4,0,6,8,5,4,6,0,7,...,3,0,2,5,9,3,1,8,8,4
3,8,8,2,5,6,9,2,3,9,9,...,2,9,3,5,4,6,2,7,3,4
4,8,8,9,6,6,1,2,9,8,3,...,4,3,0,1,4,9,5,3,9,6
5,3,5,7,8,4,5,1,0,9,6,...,3,5,0,5,7,2,4,7,9,2
6,4,1,7,7,2,3,1,8,4,1,...,0,4,3,0,3,2,6,6,2,0
7,5,9,3,5,7,0,5,4,1,7,...,1,7,3,3,7,0,6,6,5,7
8,6,5,2,0,5,0,7,2,0,2,...,0,4,4,0,9,5,9,8,2,5
9,4,6,1,5,4,6,8,7,7,1,...,3,4,0,7,6,6,3,5,7,9
10,8,1,4,9,3,7,9,9,5,3,...,3,7,2,1,5,3,5,6,9,2
11,5,6,5,1,9,3,7,3,4,4,...,8,5,8,0,8,2,8,6,9,2
12,7,3,1,7,8,3,2,8,3,1,...,7,7,7,5,8,3,1,7,8,8
13,6,5,6,6,5,6,1,4,8,4,...,9,4,6,6,0,0,7,5,4,0
14,6,3,9,0,3,8,2,1,4,2,...,5,1,7,3,0,0,2,1,2,2
15,2,0,7,3,2,7,9,9,4,6,...,4,2,7,6,7,4,2,6,1,8

In [154]:

matrix1 = numpy.array(input_matrix1)
N1 = len(matrix1)
M1= len(matrix1[0])
K1 = 2
P1 = numpy.random.rand(N1,K1)
Q1 = numpy.random.rand(M1,K1)
new_P1, new_Q1 = matrix_factorization(matrix1, P1, Q1, K1)
new_matrix1 = numpy.dot(new_P1, new_Q1.T)

Matrix Factorization Completed

Print the new matrix1

In [155]:
new_matrix1

array([[4.85405891, 4.37036192, 4.02535951, 5.39706228, 4.82595588,
        4.62334258, 3.89489065, 4.87794838, 4.49171681, 3.58771727,
        5.16700157, 5.70283934, 5.33682024, 4.94606346, 4.19411031,
        5.89950331, 3.38232391, 4.14572099, 4.58318582, 4.351604  ,
        4.51187775, 4.89698525, 4.95553901, 4.65105426, 3.39767428,
        5.24167227, 4.50440787, 5.18175053, 4.64171961, 3.97896663,
        4.63827118, 2.21922215, 5.02186323, 4.05686519, 4.75125138,
        4.29527035, 4.27398311, 5.55884942, 3.88668883, 4.08340924,
        5.30079795, 5.68785741, 4.10626844],
       [4.05029147, 3.34121509, 2.695944  , 5.48620267, 5.76484852,
        3.81980131, 4.28943791, 5.03625081, 2.86327042, 3.35006353,
        4.76367476, 6.35971637, 3.53155111, 5.482818  , 4.9332452 ,
        5.2933047 , 4.25699465, 4.17023981, 3.51906467, 6.49792962,
        4.17043382, 4.76813587, 5.16540326, 5.16394121, 4.6463873 ,
        6.40239986, 2.66248903, 5.40384923, 3.81776372, 3.64549097,
        5.02519848, 1.65427966, 5.48523527, 4.54239847, 5.34325935,
        4.16988224, 4.48224044, 6.39290884, 2.57529678, 3.5051888 ,
        6.11334062, 7.0096629 , 3.73092406],
       [3.97102967, 3.11950287, 2.30396085, 5.88180243, 6.5414629 ,
        3.72561504, 4.73745725, 5.4320603 , 2.35450184, 3.46690582,
        4.90189749, 7.05467393, 2.99082875, 6.06933424, 5.57036484,
        5.37941449, 4.90791865, 4.45248405, 3.29400842, 7.83790846,
        4.29641985, 5.02385477, 5.59164719, 5.71948449, 5.48240893,
        7.31528984, 2.04948002, 5.85085694, 3.71472736, 3.74066905,
        5.51791349, 1.52085121, 6.04057377, 5.04575546, 5.94427449,
        4.38809098, 4.86327649, 7.16568873, 2.18314731, 3.48671418,
        6.85871313, 8.03091055, 3.81379131],
       [6.08354137, 5.85787897, 5.87072568, 5.53970947, 3.88315968,
        5.84169818, 3.58645893, 4.9100338 , 6.73152909, 4.05242494,
        5.91233644, 5.1525894 , 7.83663856, 4.50988558, 3.47046607,
        6.93200245, 2.4516738 , 4.31005106, 6.12427696, 1.88232375,
        5.14932572, 5.28769128, 4.9270374 , 4.23074267, 2.00177423,
        4.04206153, 7.01075478, 5.14864094, 5.88637099, 4.58143779,
        4.37427575, 3.02732924, 4.68066629, 3.64269942, 4.23708292,
        4.65338006, 4.21544594, 4.78110214, 5.70308348, 4.99568612,
        4.5377256 , 4.30855378, 4.76688248],
       [6.43472778, 6.15910134, 6.12947404, 5.97834268, 4.31748006,
        6.17433149, 3.91918834, 5.31028656, 7.01314871, 4.32945857,
        6.30832595, 5.6436471 , 8.17759313, 4.93416431, 3.84415742,
        7.37699013, 2.76668783, 4.64483066, 6.44090999, 2.33764384,
        5.49563428, 5.67540456, 5.33606002, 4.63011442, 2.33635252,
        4.52070232, 7.28293482, 5.5764648 , 6.21948261, 4.88525706,
        4.76644656, 3.17821126, 5.10744816, 3.9929204 , 4.64839401,
        4.99284703, 4.56954963, 5.26925638, 5.95155715, 5.29591601,
        5.00406181, 4.83098935, 5.07889318],
       [4.8984439 , 4.35661899, 3.94562826, 5.61920176, 5.17564178,
        4.65894115, 4.11325707, 5.09238819, 4.37725389, 3.68318572,
        5.29375958, 6.03648994, 5.22360015, 5.22964449, 4.4845053 ,
        6.01861685, 3.66549201, 4.30862861, 4.57143577, 4.89542134,
        4.62445321, 5.06166934, 5.18201215, 4.91915339, 3.74718976,
        5.64626231, 4.3529    , 5.41902845, 4.67443211, 4.07255617,
        4.8837364 , 2.2047976 , 5.29544269, 4.29742424, 5.03709383,
        4.43754402, 4.47410041, 5.91814192, 3.80482134, 4.13796586,
        5.6464357 , 6.13783553, 4.19736707],
       [5.62602143, 5.32970934, 5.2390755 , 5.4049984 , 4.08964602,
        5.39147304, 3.61489863, 4.81786044, 5.97151841, 3.8498931 ,
        5.59741684, 5.22436311, 6.98293688, 4.55959499, 3.62068134,
        6.51699773, 2.67882833, 4.18984796, 5.576149  , 2.56309137,
        4.87842355, 5.08565426, 4.85206035, 4.28058739, 2.37078211,
        4.31997286, 6.16911566, 5.07125144, 5.42780336, 4.33021858,
        4.37658891, 2.74301404, 4.70008335, 3.70070081, 4.31390462,
        4.47146074, 4.16115265, 4.92479739, 5.08262447, 4.64807174,
        4.68129599, 4.63381845, 4.49575356],
       [5.45547364, 5.02662143, 4.77315697, 5.69648199, 4.7708726 ,
        5.21044085, 3.98690085, 5.11936104, 5.38063502, 3.89831481,
        5.63726346, 5.80780659, 6.34430487, 5.04948305, 4.17510668,
        6.49117325, 3.26232159, 4.3922331 , 5.26571395, 3.8135956 ,
        4.91847794, 5.24746288, 5.18236461, 4.7452442 , 3.13808104,
        5.12888263, 5.47431629, 5.41793293, 5.23762175, 4.34970087,
        4.77899906, 2.56837673, 5.15753023, 4.12468071, 4.82189398,
        4.60733134, 4.4593714 , 5.58836259, 4.61916063, 4.55254314,
        5.32247791, 5.54206892, 4.50058637],
       [5.04262865, 4.62462502, 4.36506427, 5.3349099 , 4.5327577 ,
        4.8134528 , 3.75870981, 4.80027485, 4.91088353, 3.62851694,
        5.24264809, 5.48154489, 5.79901857, 4.76324911, 3.96054872,
        6.02616813, 3.11691784, 4.11013522, 4.84564297, 3.72776489,
        4.57496131, 4.89859631, 4.86306605, 4.47689064, 3.02871361,
        4.88423333, 4.98252596, 5.08432219, 4.83734815, 4.04354912,
        4.49903273, 2.36004764, 4.85881743, 3.89439516, 4.55450928,
        4.30010489, 4.18669005, 5.28955252, 4.22237238, 4.21495451,
        5.03924484, 5.28276944, 4.18154596],
       [5.82258184, 5.39693657, 5.16393151, 5.97664247, 4.90947644,
        5.56504681, 4.14607238, 5.36244914, 5.83557074, 4.12322569,
        5.96913147, 6.03054885, 6.86795935, 5.24695936, 4.3055711 ,
        6.88906559, 3.33124611, 4.61316177, 5.65209006, 3.76928481,
        5.20686886, 5.52898225, 5.42293131, 4.92988079, 3.15911564,
        5.26106611, 5.95774333, 5.66913532, 5.59588024, 4.60824413,
        4.97935109, 2.76193528, 5.36866258, 4.28075765, 5.00164166,
        4.85587049, 4.66330173, 5.78024221, 5.00009088, 4.8486112 ,
        5.50320959, 5.67739293, 4.7714652 ],
       [5.40614187, 4.76725003, 4.26579897, 6.33322412, 5.94482742,
        5.13672991, 4.67878518, 5.74955969, 4.71245529, 4.11266169,
        5.90299754, 6.87657535, 5.64158119, 5.9532355 , 5.14129465,
        6.69205718, 4.23754424, 4.85041328, 5.00436714, 5.78674652,
        5.15808073, 5.67762317, 5.8570986 , 5.60082519, 4.37814249,
        6.50315271, 4.65726999, 6.12533526, 5.15149998, 4.5382319 ,
        5.54458515, 2.40686783, 6.01770671, 4.89781725, 5.74380754,
        4.97593061, 5.06048634, 6.76649675, 4.10973678, 4.5799603 ,
        6.45802556, 7.07714128, 4.67319465],
       [5.35769824, 4.60140185, 3.96038548, 6.67262715, 6.59210929,
        5.07539258, 5.05585473, 6.08742263, 4.31363327, 4.21947566,
        6.03239772, 7.46036066, 5.21956592, 6.44636543, 5.67308672,
        6.78150388, 4.77788406, 5.09353602, 4.8365016 , 6.89047452,
        5.2753738 , 5.90165669, 6.21996008, 6.0678023 , 5.06901526,
        7.26259507, 4.17374344, 6.50582291, 5.08302819, 4.62872236,
        5.96044143, 2.30570484, 6.48573925, 5.32040946, 6.24808296,
        5.16748597, 5.38434841, 7.4130763 , 3.80373112, 4.57839651,
        7.08147286, 7.92614756, 4.75409604],
       [4.23527593, 3.27010727, 2.33363295, 6.45651878, 7.30093596,
        3.96644684, 5.24659471, 5.97371631, 2.34616439, 3.76408787,
        5.31244458, 7.8227784 , 3.01795478, 6.72609116, 6.20844269,
        5.80652069, 5.50212294, 4.88138609, 3.45627473, 8.89421679,
        4.65798487, 5.48537443, 6.15593668, 6.33939763, 6.18508406,
        8.18047357, 1.98141943, 6.44166396, 3.95159441, 4.05027924,
        6.10052398, 1.58522117, 6.68407037, 5.59738205, 6.59699866,
        4.78936572, 5.35774737, 7.96978214, 2.20385889, 3.73700019,
        7.63039572, 8.98754008, 4.12438961],
       [6.07990077, 5.90648462, 5.98029254, 5.368733  , 3.58434628,
        5.84468094, 3.40698438, 4.74229946, 6.87841948, 3.98919677,
        5.83164652, 4.87635591, 7.98915988, 4.2759058 , 3.22382486,
        6.86461908, 2.20545208, 4.18618191, 6.17267773, 1.39212896,
        5.07704145, 5.16817892, 4.74830511, 4.00933489, 1.6915796 ,
        3.69356677, 7.19353622, 4.96129898, 5.89229047, 4.52318756,
        4.17463085, 3.05920415, 4.45696158, 3.44309434, 3.99934361,
        4.55065391, 4.05666602, 4.47893249, 5.81359314, 4.97598918,
        4.24666154, 3.91981728, 4.71206775],
       [5.72858199, 5.53422696, 5.56754811, 5.1581164 , 3.55337546,
        5.50310503, 3.31546793, 4.56617817, 6.39129789, 3.79480983,
        5.54050898, 4.75686193, 7.43411741, 4.1662334 , 3.18283728,
        6.50552462, 2.22342278, 4.01634793, 5.78506547, 1.60224431,
        4.82478517, 4.93866561, 4.57836468, 3.90769609, 1.77741026,
        3.68574421, 6.66678373, 4.78408724, 5.54620291, 4.29479919,
        4.0504602 , 2.86241887, 4.33066194, 3.36143097, 3.90798252,
        4.3470762 , 3.91509021, 4.39794394, 5.40998068, 4.69838433,
        4.1725831 , 3.92273419, 4.47065822],
       [5.18309317, 4.64838146, 4.2586676 , 5.82154779, 5.25678949,
        4.9344716 , 4.22093213, 5.26624334, 4.74340213, 3.8521794 ,
        5.54423445, 6.18494926, 5.64359036, 5.36223032, 4.56395193,
        6.3215214 , 3.6972048 , 4.46916433, 4.87564761, 4.8176425 ,
        4.84192244, 5.26962479, 5.35293672, 5.04288487, 3.73606592,
        5.71802935, 4.74434126, 5.59744713, 4.95305777, 4.26809787,
        5.02159316, 2.35787031, 5.4395385 , 4.40091553, 5.15558491,
        4.62138382, 4.61835142, 6.04034847, 4.1103024 , 4.36604852,
        5.76097139, 6.20847906, 4.40278841]])

Now take input2.csv file as input and run matrix factorization on that input file

In [157]:
input_matrix2 = pd.read_csv("input2.csv", header=None)
input_matrix2

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,8,0,0,4,0,1,8,6,9,8,...,0,5,0,1,8,6,3,2,0,0
1,6,2,0,3,9,0,7,0,2,1,...,4,7,7,3,2,0,3,0,2,8
2,5,4,2,8,3,7,7,0,9,4,...,6,8,0,5,8,9,8,1,2,9
3,9,8,7,8,4,5,5,9,5,9,...,1,1,8,9,9,5,8,4,3,4
4,6,0,2,2,7,3,3,3,5,7,...,8,9,6,2,9,5,7,0,8,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,7,5,9,0,2,3,9,3,9,2,...,5,4,9,5,7,6,0,0,2,1
163,2,3,2,3,8,0,8,4,4,6,...,6,6,5,2,4,5,7,8,8,1
164,4,5,4,0,3,2,2,9,0,6,...,2,6,0,4,2,5,6,1,1,4
165,7,4,4,7,4,9,2,0,4,8,...,1,1,7,8,0,6,1,3,1,5
166,0,7,4,5,8,0,1,5,4,3,...,2,5,4,6,5,3,4,4,7,5

In [158]:
matrix2 = numpy.array(input_matrix2)
N2 = len(matrix2)
M2= len(matrix2[0])
K2 = 2
P2 = numpy.random.rand(N2,K2)
Q2 = numpy.random.rand(M2,K2)
new_P2, new_Q2 = matrix_factorization(matrix2, P2, Q2, K2)
new_matrix2 = numpy.dot(new_P2, new_Q2.T)

Matrix Factorization Completed

Print the new matrix2

In [159]:
new_matrix2

array([[5.05467583, 5.17586741, 5.03475093, ..., 4.69891142, 5.03913678,
        4.75274452],
       [5.012207  , 4.05161368, 3.37539958, ..., 5.18510459, 4.18914073,
        6.60368182],
       [5.36350702, 5.01532823, 4.62901104, ..., 5.21790412, 4.99072426,
        5.87727609],
       ...,
       [4.70552792, 4.51554714, 4.23392632, ..., 4.52161678, 4.46477868,
        4.95422197],
       [4.75695951, 3.90699053, 3.29583163, ..., 4.89103917, 4.02192094,
        6.15942976],
       [5.61668226, 5.42009837, 5.09892333, ..., 5.38247844, 5.35187195,
        5.86072368]])